dependencies:
  - name: nats
    version: 1.3.1
    repository: "@stable"
    condition: nats.enabled
  - name: cockroachdb
    version: 2.0.3
    repository: "@stable"
    condition: cockroachdb.enabled
