#
# Ref:
#   https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html
#

cluster.name: es-local
node.name: es-local

# https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html
network:
  host: 0.0.0.0

discovery:
  type: single-node

# path:
#   logs: /var/log/elasticsearch
#   data: /var/data/elasticsearch
