dist: trusty
sudo: required

services:
  - docker

jobs:
  include:

    - stage: unit tests
      language: go
      go: 1.9.2
      script:
        - cd services/sensor-service
        - make test

    - stage: unit tests
      language: node_js
      node_js: 9
      script:
        - cd services/site-service
        - yarn
        - yarn run nsp
        - yarn run lint
        - yarn run test

    - stage: component tests
      language: go
      go: 1.9.2
      script:
        - cd services/sensor-service
        - make docker up
        - make test-component

    - stage: component tests
      language: node_js
      node_js: 9
      script:
        - cd services/site-service
        - make docker docker-test up
        - yarn && yarn run test:component

    - stage: integration tests
      language: generic
      script:
        - cd compose
        - make fluentd services
        - make test-up && sleep 10
        - make test-integration
