dist: trusty
sudo: required

services:
  - docker

matrix:
  include:

    - stage: test
      language: go
      go: 1.9.2
      script:
        - make test-go-service

    - stage: test
      language: node_js
      node_js: 9
      install:
        - npm install -g yarn
      script:
        - make test-node-service
