# https://docs.traefik.io/basics
# https://docs.traefik.io/user-guide/examples
# https://docs.traefik.io/configuration/commons
# https://docs.traefik.io/configuration/api
# https://docs.traefik.io/configuration/metrics
# https://docs.traefik.io/configuration/entrypoints
# https://docs.traefik.io/configuration/backends/rest
# https://docs.traefik.io/configuration/backends/docker


logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[traefikLog]
format = "json"

[accessLog]
format = "json"

[api]
entryPoint = "traefik"
dashboard = true

[metrics]
  [metrics.prometheus]
  entryPoint = "traefik"
  buckets = [0.01, 0.1, 0.5 , 1.0, 5.0]

# Docker Backend
[docker]
domain = "demo.docker"
watch = true
exposedbydefault = false

# http redirect on https
[entryPoints]
  [entryPoints.http]
  address = ":80"
    # [entryPoints.http.redirect]
    # entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/certs/traefik.cert"
      keyFile = "/etc/ssl/certs/traefik.key"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/certs/localhost.cert"
      keyFile = "/etc/ssl/certs/localhost.key"
