version: "3.4"
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    volumes:
      - "./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
  sensor-service:
    image: moorara/sensor-service:${VERSION:-latest}
    hostname: sensor-service
    container_name: sensor-service
    depends_on:
      - postgres
    ports:
      - "4020:4020"
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_URL=postgres://root:pass@postgres
  sensor-service-test:
    image: sensor-service-test
    hostname: sensor-service-test
    container_name: sensor-service-test
    depends_on:
      - sensor-service
    environment:
      - SERVICE_URL=http://sensor-service:4020
