apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "asset.fullname" . }}
  labels:
    app: {{ template "asset.name" . }}
    chart: {{ template "asset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.nats.enabled }}
  {{- if .Values.nats.auth.password }}
  nats-password: {{ .Values.nats.auth.password | b64enc }}
  {{- end }}
  {{- else if .Values.nats.external.servers }}
  {{- if .Values.nats.external.password }}
  nats-password: {{ .Values.nats.external.password | b64enc }}
  {{- end }}
  {{- end }}

  {{- if .Values.cockroachdb.enabled }}
  {{- if .Values.cockroachdb.password }}
  cockroach-password: {{ .Values.cockroachdb.password | b64enc }}
  {{- end }}
  {{- else if .Values.cockroachdb.external.addr }}
  {{- if .Values.cockroachdb.external.password }}
  cockroach-password: {{ .Values.cockroachdb.external.password | b64enc }}
  {{- end }}
  {{- end }}
