{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "asset.serviceAccountName" . }}
  labels:
    app: {{ template "asset.name" . }}
    chart: {{ template "asset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
