version: "3.7"
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    volumes:
      - "./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql"

  sensor-service:
    image: moorara/sensor-service:${VERSION:-latest}
    hostname: sensor-service
    container_name: sensor-service
    depends_on:
      - postgres
    ports:
      - "4020:4020"
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=pass

  component-test:
    image: sensor-service-test
    hostname: component-test
    container_name: component-test
    depends_on:
      - sensor-service
    environment:
      - SERVICE_URL=http://sensor-service:4020
    command: [ "go", "test", "-v", "./test/component" ]
