## This is a YAML-formatted file
##

go-job: &go-job
  working_directory: ~/repo
  docker:
    - image: moorara/golang:latest

node-job: &node-job
  working_directory: ~/repo
  docker:
    - image: moorara/node:latest

generic-job: &generic-job
  working_directory: ~/repo
  docker:
    - image: moorara/tools:latest


version: 2
jobs:

  react-client-unit-tests:
    <<: *node-job
    steps:
      - checkout
      - run:
          name: Install Packages
          working_directory: services/react-client
          command: yarn install
      - run:
          name: Linting
          working_directory: services/react-client
          command: yarn run lint
      - run:
          name: Unit Testing
          working_directory: services/react-client
          command: yarn run test:coverage
      - store_artifacts:
          path: services/react-client/coverage

  react-client-build-app:
    <<: *node-job
    steps:
      - checkout
      - run:
          name: Install Packages
          working_directory: services/react-client
          command: yarn install
      - run:
          name: Build App
          working_directory: services/react-client
          command: yarn run build
      - store_artifacts:
          path: services/react-client/public

  react-client-build-images:
    <<: *generic-job
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker Image
          working_directory: services/react-client
          command: make docker
      - run:
          name: Save Docker Images
          working_directory: services/react-client
          command: make save-images
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker.tar

  site-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/site
          command: helm lint .

  sensor-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/sensor
          command: helm lint .

  asset-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/asset
          command: helm lint .


workflows:
  version: 2
  react-client:
    jobs:
      - react-client-unit-tests
      - react-client-build-app
      - react-client-build-images
  site-chart:
    jobs:
      - site-chart-tests
  sensor-chart:
    jobs:
      - sensor-chart-tests
  asset-chart:
    jobs:
      - asset-chart-tests
