## This is a YAML-formatted file
##

go-job: &go-job
  working_directory: ~/repo
  docker:
    - image: moorara/golang:latest

node-job: &node-job
  working_directory: ~/repo
  docker:
    - image: moorara/node:latest

generic-job: &generic-job
  working_directory: ~/repo
  docker:
    - image: moorara/tools:latest


version: 2
jobs:

  sensor-service-unit-tests:
    <<: *go-job
    steps:
      - checkout
      - run:
          name: Unit Testing
          working_directory: services/sensor
          command: make test
      - run:
          name: Unit Testing + Coverage
          working_directory: services/sensor
          command: make coverage
      - store_artifacts:
          path: services/sensor/coverage/

  sensor-service-build-images:
    <<: *generic-job
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker Image
          working_directory: services/sensor
          command: make docker
      - run:
          name: Save Docker Images
          working_directory: services/sensor
          command: make save-docker
      - persist_to_workspace:
          root: services/sensor
          paths:
            - docker.tar

  sensor-service-component-tests:
    <<: *generic-job
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: services/sensor
      - run:
          name: Load Docker Images
          working_directory: services/sensor
          command: make load-docker
      - run:
          name: Build Docker Test Image
          working_directory: services/sensor
          command: make docker-test
      - run:
          name: Component Testing
          working_directory: services/sensor
          command: |
            # This is a very hacky trick since we cannot mount a volume
            docker-compose up -d postgres
            sleep 4
            docker exec postgres psql -c "CREATE DATABASE sensors"
            docker exec postgres psql -d sensors -c "CREATE TABLE sensors (id varchar(256) PRIMARY KEY, site_id varchar(256) NOT NULL, name varchar(256) NOT NULL, unit varchar(256) NOT NULL, min_safe double precision NOT NULL, max_safe double precision NOT NULL)"
            make test-component-docker
      - store_artifacts:
          path: services/sensor/component-tests.log
          destination: component-tests.log

  switch-service-unit-tests:
    <<: *go-job
    steps:
      - checkout
      - run:
          name: Unit Testing
          working_directory: services/switch-service
          command: make test
      - run:
          name: Unit Testing + Coverage
          working_directory: services/switch-service
          command: make coverage
      - store_artifacts:
          path: services/switch-service/coverage/

  switch-service-build-images:
    <<: *generic-job
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker Image
          working_directory: services/switch-service
          command: make docker
      - run:
          name: Build Docker Test Image
          working_directory: services/switch-service
          command: make docker-test
      - run:
          name: Save Docker Images
          working_directory: services/switch-service
          command: make save-images
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker.tar
            - docker-test.tar

  switch-service-integration-tests:
    <<: *generic-job
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Load Docker Images
          command: |
            docker image load -i /tmp/workspace/docker.tar
            docker image load -i /tmp/workspace/docker-test.tar
      - run:
          name: Integration Testing
          working_directory: services/switch-service
          command: make test-integration-docker

  switch-service-component-tests:
    <<: *generic-job
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Load Docker Images
          command: |
            docker image load -i /tmp/workspace/docker.tar
            docker image load -i /tmp/workspace/docker-test.tar
      - run:
          name: Component Testing
          working_directory: services/switch-service
          command: make test-component-docker
      - store_artifacts:
          path: services/switch-service/component-tests.log
          destination: component-tests.log

  asset-service-unit-tests:
    <<: *go-job
    steps:
      - checkout
      - run:
          name: Unit Testing
          working_directory: services/asset-service
          command: make test
      - run:
          name: Unit Testing + Coverage
          working_directory: services/asset-service
          command: make coverage
      - store_artifacts:
          path: services/asset-service/coverage/

  asset-service-build-images:
    <<: *generic-job
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker Image
          working_directory: services/asset-service
          command: make docker
      - run:
          name: Build Docker Test Image
          working_directory: services/asset-service
          command: make docker-test
      - run:
          name: Save Docker Images
          working_directory: services/asset-service
          command: make save-images
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker.tar
            - docker-test.tar

  asset-service-integration-tests:
    <<: *generic-job
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Load Docker Images
          command: |
            docker image load -i /tmp/workspace/docker.tar
            docker image load -i /tmp/workspace/docker-test.tar
      - run:
          name: Integration Testing
          working_directory: services/asset-service
          command: make test-integration-docker

  asset-service-component-tests:
    <<: *generic-job
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Load Docker Images
          command: |
            docker image load -i /tmp/workspace/docker.tar
            docker image load -i /tmp/workspace/docker-test.tar
      - run:
          name: Component Testing
          working_directory: services/asset-service
          command: make test-component-docker
      - store_artifacts:
          path: services/asset-service/component-tests.log
          destination: component-tests.log

  graphql-server-unit-tests:
    <<: *node-job
    steps:
      - checkout
      - run:
          name: Install Packages
          working_directory: services/graphql-server
          command: yarn install
      - run:
          name: Linting
          working_directory: services/graphql-server
          command: yarn run lint
      - run:
          name: Unit Testing
          working_directory: services/graphql-server
          command: yarn run test
      - store_artifacts:
          path: services/graphql-server/coverage/

  graphql-server-build-images:
    <<: *generic-job
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker Image
          working_directory: services/graphql-server
          command: make docker
      - run:
          name: Build Docker Test Image
          working_directory: services/graphql-server
          command: make docker-test
      - run:
          name: Save Docker Images
          working_directory: services/graphql-server
          command: make save-images
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker.tar
            - docker-test.tar

  graphql-server-component-tests:
    <<: *generic-job
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Load Docker Images
          command: |
            docker image load -i /tmp/workspace/docker.tar
            docker image load -i /tmp/workspace/docker-test.tar
      - run:
          name: Component Testing
          working_directory: services/graphql-server
          command: make test-component-docker
      - store_artifacts:
          path: services/graphql-server/component-tests.log
          destination: component-tests.log

  react-client-unit-tests:
    <<: *node-job
    steps:
      - checkout
      - run:
          name: Install Packages
          working_directory: services/react-client
          command: yarn install
      - run:
          name: Linting
          working_directory: services/react-client
          command: yarn run lint
      - run:
          name: Unit Testing
          working_directory: services/react-client
          command: yarn run test:coverage
      - store_artifacts:
          path: services/react-client/coverage

  react-client-build-app:
    <<: *node-job
    steps:
      - checkout
      - run:
          name: Install Packages
          working_directory: services/react-client
          command: yarn install
      - run:
          name: Build App
          working_directory: services/react-client
          command: yarn run build
      - store_artifacts:
          path: services/react-client/public

  react-client-build-images:
    <<: *generic-job
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker Image
          working_directory: services/react-client
          command: make docker
      - run:
          name: Save Docker Images
          working_directory: services/react-client
          command: make save-images
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker.tar

  site-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/site
          command: helm lint .

  sensor-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/sensor
          command: helm lint .

  asset-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/asset
          command: helm lint .


workflows:
  version: 2
  sensor-service:
    jobs:
      - sensor-service-unit-tests
      - sensor-service-build-images
      - sensor-service-component-tests:
          requires:
            - sensor-service-build-images
  switch-service:
    jobs:
      - switch-service-unit-tests
      - switch-service-build-images
      - switch-service-integration-tests:
          requires:
            - switch-service-build-images
      - switch-service-component-tests:
          requires:
            - switch-service-build-images
  asset-service:
    jobs:
      - asset-service-unit-tests
      - asset-service-build-images
      - asset-service-integration-tests:
          requires:
            - asset-service-build-images
      - asset-service-component-tests:
          requires:
            - asset-service-build-images
  graphql-server:
    jobs:
      - graphql-server-unit-tests
      - graphql-server-build-images
      - graphql-server-component-tests:
          requires:
            - graphql-server-build-images
  react-client:
    jobs:
      - react-client-unit-tests
      - react-client-build-app
      - react-client-build-images
  site-chart:
    jobs:
      - site-chart-tests
  sensor-chart:
    jobs:
      - sensor-chart-tests
  asset-chart:
    jobs:
      - asset-chart-tests
