## This is a YAML-formatted file
##

go-job: &go-job
  working_directory: ~/repo
  docker:
    - image: moorara/golang:latest

node-job: &node-job
  working_directory: ~/repo
  docker:
    - image: moorara/node:latest

generic-job: &generic-job
  working_directory: ~/repo
  docker:
    - image: moorara/tools:latest


version: 2
jobs:

  site-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/site
          command: helm lint .

  sensor-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/sensor
          command: helm lint .

  asset-chart-tests:
    <<: *generic-job
    steps:
      - checkout
      - run:
          name: Linting
          working_directory: charts/asset
          command: helm lint .


workflows:
  version: 2
  site-chart:
    jobs:
      - site-chart-tests
  sensor-chart:
    jobs:
      - sensor-chart-tests
  asset-chart:
    jobs:
      - asset-chart-tests
