// Code generated by protoc-gen-go. DO NOT EDIT.
// source: switch.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Switch struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteId               string   `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	States               []string `protobuf:"bytes,5,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Switch) Reset()         { *m = Switch{} }
func (m *Switch) String() string { return proto.CompactTextString(m) }
func (*Switch) ProtoMessage()    {}
func (*Switch) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{0}
}
func (m *Switch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Switch.Unmarshal(m, b)
}
func (m *Switch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Switch.Marshal(b, m, deterministic)
}
func (dst *Switch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Switch.Merge(dst, src)
}
func (m *Switch) XXX_Size() int {
	return xxx_messageInfo_Switch.Size(m)
}
func (m *Switch) XXX_DiscardUnknown() {
	xxx_messageInfo_Switch.DiscardUnknown(m)
}

var xxx_messageInfo_Switch proto.InternalMessageInfo

func (m *Switch) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Switch) GetSiteId() string {
	if m != nil {
		return m.SiteId
	}
	return ""
}

func (m *Switch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Switch) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Switch) GetStates() []string {
	if m != nil {
		return m.States
	}
	return nil
}

type InstallSwitchRequest struct {
	SiteId               string   `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	States               []string `protobuf:"bytes,4,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSwitchRequest) Reset()         { *m = InstallSwitchRequest{} }
func (m *InstallSwitchRequest) String() string { return proto.CompactTextString(m) }
func (*InstallSwitchRequest) ProtoMessage()    {}
func (*InstallSwitchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{1}
}
func (m *InstallSwitchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSwitchRequest.Unmarshal(m, b)
}
func (m *InstallSwitchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSwitchRequest.Marshal(b, m, deterministic)
}
func (dst *InstallSwitchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSwitchRequest.Merge(dst, src)
}
func (m *InstallSwitchRequest) XXX_Size() int {
	return xxx_messageInfo_InstallSwitchRequest.Size(m)
}
func (m *InstallSwitchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSwitchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSwitchRequest proto.InternalMessageInfo

func (m *InstallSwitchRequest) GetSiteId() string {
	if m != nil {
		return m.SiteId
	}
	return ""
}

func (m *InstallSwitchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstallSwitchRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *InstallSwitchRequest) GetStates() []string {
	if m != nil {
		return m.States
	}
	return nil
}

type RemoveSwitchRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSwitchRequest) Reset()         { *m = RemoveSwitchRequest{} }
func (m *RemoveSwitchRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveSwitchRequest) ProtoMessage()    {}
func (*RemoveSwitchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{2}
}
func (m *RemoveSwitchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSwitchRequest.Unmarshal(m, b)
}
func (m *RemoveSwitchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSwitchRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveSwitchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSwitchRequest.Merge(dst, src)
}
func (m *RemoveSwitchRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveSwitchRequest.Size(m)
}
func (m *RemoveSwitchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSwitchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSwitchRequest proto.InternalMessageInfo

func (m *RemoveSwitchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveSwitchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSwitchResponse) Reset()         { *m = RemoveSwitchResponse{} }
func (m *RemoveSwitchResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveSwitchResponse) ProtoMessage()    {}
func (*RemoveSwitchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{3}
}
func (m *RemoveSwitchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSwitchResponse.Unmarshal(m, b)
}
func (m *RemoveSwitchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSwitchResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveSwitchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSwitchResponse.Merge(dst, src)
}
func (m *RemoveSwitchResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveSwitchResponse.Size(m)
}
func (m *RemoveSwitchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSwitchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSwitchResponse proto.InternalMessageInfo

type GetSwitchRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSwitchRequest) Reset()         { *m = GetSwitchRequest{} }
func (m *GetSwitchRequest) String() string { return proto.CompactTextString(m) }
func (*GetSwitchRequest) ProtoMessage()    {}
func (*GetSwitchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{4}
}
func (m *GetSwitchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSwitchRequest.Unmarshal(m, b)
}
func (m *GetSwitchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSwitchRequest.Marshal(b, m, deterministic)
}
func (dst *GetSwitchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSwitchRequest.Merge(dst, src)
}
func (m *GetSwitchRequest) XXX_Size() int {
	return xxx_messageInfo_GetSwitchRequest.Size(m)
}
func (m *GetSwitchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSwitchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSwitchRequest proto.InternalMessageInfo

func (m *GetSwitchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetSwitchesRequest struct {
	SiteId               string   `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSwitchesRequest) Reset()         { *m = GetSwitchesRequest{} }
func (m *GetSwitchesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSwitchesRequest) ProtoMessage()    {}
func (*GetSwitchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{5}
}
func (m *GetSwitchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSwitchesRequest.Unmarshal(m, b)
}
func (m *GetSwitchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSwitchesRequest.Marshal(b, m, deterministic)
}
func (dst *GetSwitchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSwitchesRequest.Merge(dst, src)
}
func (m *GetSwitchesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSwitchesRequest.Size(m)
}
func (m *GetSwitchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSwitchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSwitchesRequest proto.InternalMessageInfo

func (m *GetSwitchesRequest) GetSiteId() string {
	if m != nil {
		return m.SiteId
	}
	return ""
}

type SetSwitchRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSwitchRequest) Reset()         { *m = SetSwitchRequest{} }
func (m *SetSwitchRequest) String() string { return proto.CompactTextString(m) }
func (*SetSwitchRequest) ProtoMessage()    {}
func (*SetSwitchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{6}
}
func (m *SetSwitchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSwitchRequest.Unmarshal(m, b)
}
func (m *SetSwitchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSwitchRequest.Marshal(b, m, deterministic)
}
func (dst *SetSwitchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSwitchRequest.Merge(dst, src)
}
func (m *SetSwitchRequest) XXX_Size() int {
	return xxx_messageInfo_SetSwitchRequest.Size(m)
}
func (m *SetSwitchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSwitchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSwitchRequest proto.InternalMessageInfo

func (m *SetSwitchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetSwitchRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type SetSwitchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSwitchResponse) Reset()         { *m = SetSwitchResponse{} }
func (m *SetSwitchResponse) String() string { return proto.CompactTextString(m) }
func (*SetSwitchResponse) ProtoMessage()    {}
func (*SetSwitchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_switch_66fc13a4912a9ddf, []int{7}
}
func (m *SetSwitchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSwitchResponse.Unmarshal(m, b)
}
func (m *SetSwitchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSwitchResponse.Marshal(b, m, deterministic)
}
func (dst *SetSwitchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSwitchResponse.Merge(dst, src)
}
func (m *SetSwitchResponse) XXX_Size() int {
	return xxx_messageInfo_SetSwitchResponse.Size(m)
}
func (m *SetSwitchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSwitchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetSwitchResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Switch)(nil), "proto.Switch")
	proto.RegisterType((*InstallSwitchRequest)(nil), "proto.InstallSwitchRequest")
	proto.RegisterType((*RemoveSwitchRequest)(nil), "proto.RemoveSwitchRequest")
	proto.RegisterType((*RemoveSwitchResponse)(nil), "proto.RemoveSwitchResponse")
	proto.RegisterType((*GetSwitchRequest)(nil), "proto.GetSwitchRequest")
	proto.RegisterType((*GetSwitchesRequest)(nil), "proto.GetSwitchesRequest")
	proto.RegisterType((*SetSwitchRequest)(nil), "proto.SetSwitchRequest")
	proto.RegisterType((*SetSwitchResponse)(nil), "proto.SetSwitchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SwitchServiceClient is the client API for SwitchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SwitchServiceClient interface {
	InstallSwitch(ctx context.Context, in *InstallSwitchRequest, opts ...grpc.CallOption) (*Switch, error)
	RemoveSwitch(ctx context.Context, in *RemoveSwitchRequest, opts ...grpc.CallOption) (*RemoveSwitchResponse, error)
	GetSwitch(ctx context.Context, in *GetSwitchRequest, opts ...grpc.CallOption) (*Switch, error)
	GetSwitches(ctx context.Context, in *GetSwitchesRequest, opts ...grpc.CallOption) (SwitchService_GetSwitchesClient, error)
	SetSwitch(ctx context.Context, in *SetSwitchRequest, opts ...grpc.CallOption) (*SetSwitchResponse, error)
}

type switchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSwitchServiceClient(cc *grpc.ClientConn) SwitchServiceClient {
	return &switchServiceClient{cc}
}

func (c *switchServiceClient) InstallSwitch(ctx context.Context, in *InstallSwitchRequest, opts ...grpc.CallOption) (*Switch, error) {
	out := new(Switch)
	err := c.cc.Invoke(ctx, "/proto.SwitchService/InstallSwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchServiceClient) RemoveSwitch(ctx context.Context, in *RemoveSwitchRequest, opts ...grpc.CallOption) (*RemoveSwitchResponse, error) {
	out := new(RemoveSwitchResponse)
	err := c.cc.Invoke(ctx, "/proto.SwitchService/RemoveSwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchServiceClient) GetSwitch(ctx context.Context, in *GetSwitchRequest, opts ...grpc.CallOption) (*Switch, error) {
	out := new(Switch)
	err := c.cc.Invoke(ctx, "/proto.SwitchService/GetSwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchServiceClient) GetSwitches(ctx context.Context, in *GetSwitchesRequest, opts ...grpc.CallOption) (SwitchService_GetSwitchesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SwitchService_serviceDesc.Streams[0], "/proto.SwitchService/GetSwitches", opts...)
	if err != nil {
		return nil, err
	}
	x := &switchServiceGetSwitchesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SwitchService_GetSwitchesClient interface {
	Recv() (*Switch, error)
	grpc.ClientStream
}

type switchServiceGetSwitchesClient struct {
	grpc.ClientStream
}

func (x *switchServiceGetSwitchesClient) Recv() (*Switch, error) {
	m := new(Switch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *switchServiceClient) SetSwitch(ctx context.Context, in *SetSwitchRequest, opts ...grpc.CallOption) (*SetSwitchResponse, error) {
	out := new(SetSwitchResponse)
	err := c.cc.Invoke(ctx, "/proto.SwitchService/SetSwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchServiceServer is the server API for SwitchService service.
type SwitchServiceServer interface {
	InstallSwitch(context.Context, *InstallSwitchRequest) (*Switch, error)
	RemoveSwitch(context.Context, *RemoveSwitchRequest) (*RemoveSwitchResponse, error)
	GetSwitch(context.Context, *GetSwitchRequest) (*Switch, error)
	GetSwitches(*GetSwitchesRequest, SwitchService_GetSwitchesServer) error
	SetSwitch(context.Context, *SetSwitchRequest) (*SetSwitchResponse, error)
}

func RegisterSwitchServiceServer(s *grpc.Server, srv SwitchServiceServer) {
	s.RegisterService(&_SwitchService_serviceDesc, srv)
}

func _SwitchService_InstallSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchServiceServer).InstallSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SwitchService/InstallSwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchServiceServer).InstallSwitch(ctx, req.(*InstallSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchService_RemoveSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchServiceServer).RemoveSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SwitchService/RemoveSwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchServiceServer).RemoveSwitch(ctx, req.(*RemoveSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchService_GetSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchServiceServer).GetSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SwitchService/GetSwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchServiceServer).GetSwitch(ctx, req.(*GetSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchService_GetSwitches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSwitchesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SwitchServiceServer).GetSwitches(m, &switchServiceGetSwitchesServer{stream})
}

type SwitchService_GetSwitchesServer interface {
	Send(*Switch) error
	grpc.ServerStream
}

type switchServiceGetSwitchesServer struct {
	grpc.ServerStream
}

func (x *switchServiceGetSwitchesServer) Send(m *Switch) error {
	return x.ServerStream.SendMsg(m)
}

func _SwitchService_SetSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchServiceServer).SetSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SwitchService/SetSwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchServiceServer).SetSwitch(ctx, req.(*SetSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SwitchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SwitchService",
	HandlerType: (*SwitchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallSwitch",
			Handler:    _SwitchService_InstallSwitch_Handler,
		},
		{
			MethodName: "RemoveSwitch",
			Handler:    _SwitchService_RemoveSwitch_Handler,
		},
		{
			MethodName: "GetSwitch",
			Handler:    _SwitchService_GetSwitch_Handler,
		},
		{
			MethodName: "SetSwitch",
			Handler:    _SwitchService_SetSwitch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSwitches",
			Handler:       _SwitchService_GetSwitches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "switch.proto",
}

func init() { proto.RegisterFile("switch.proto", fileDescriptor_switch_66fc13a4912a9ddf) }

var fileDescriptor_switch_66fc13a4912a9ddf = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x51, 0x4f, 0xc2, 0x30,
	0x10, 0xc7, 0xb3, 0x02, 0x33, 0x9c, 0x60, 0xf0, 0x20, 0x50, 0xc7, 0x0b, 0x69, 0x62, 0xe2, 0x8b,
	0xc4, 0xc8, 0x8b, 0xc6, 0xc4, 0x57, 0xc2, 0xeb, 0xf6, 0x01, 0xcc, 0x64, 0x97, 0xd8, 0x04, 0x36,
	0xa0, 0x15, 0x3f, 0xa1, 0xdf, 0xcb, 0xd8, 0x2e, 0x73, 0x2b, 0x8d, 0x3c, 0xad, 0xfd, 0xff, 0xef,
	0xfa, 0xbf, 0xfb, 0x0d, 0x7a, 0xea, 0x4b, 0xea, 0xf5, 0xc7, 0x7c, 0x77, 0x28, 0x74, 0x81, 0x1d,
	0xf3, 0x11, 0x0a, 0xc2, 0xc4, 0xc8, 0x78, 0x05, 0x4c, 0x66, 0x3c, 0x98, 0x05, 0x77, 0xdd, 0x98,
	0xc9, 0x0c, 0x27, 0x70, 0xa1, 0xa4, 0xa6, 0x37, 0x99, 0x71, 0x66, 0xc4, 0xf0, 0xf7, 0xba, 0xca,
	0x10, 0xa1, 0x9d, 0xa7, 0x5b, 0xe2, 0x2d, 0xa3, 0x9a, 0x33, 0x8e, 0xa0, 0xa3, 0x74, 0xaa, 0x89,
	0xb7, 0x8d, 0x68, 0x2f, 0x38, 0x86, 0xd0, 0x1c, 0x14, 0xef, 0xcc, 0x5a, 0xe6, 0x05, 0x73, 0x13,
	0x7b, 0x18, 0xad, 0x72, 0xa5, 0xd3, 0xcd, 0xc6, 0x66, 0xc7, 0xb4, 0xff, 0x24, 0xa5, 0xeb, 0x91,
	0x81, 0x37, 0x92, 0xf9, 0x22, 0x5b, 0xfe, 0xc8, 0x76, 0x23, 0xf2, 0x16, 0x86, 0x31, 0x6d, 0x8b,
	0x23, 0x35, 0x13, 0x9d, 0xa5, 0xc5, 0x18, 0x46, 0xcd, 0x32, 0xb5, 0x2b, 0x72, 0x45, 0x42, 0xc0,
	0x60, 0x49, 0xfa, 0xff, 0xde, 0x7b, 0xc0, 0xaa, 0x86, 0xd4, 0xb9, 0x9d, 0xc4, 0x13, 0x0c, 0x92,
	0x33, 0x4f, 0xfe, 0xed, 0xc8, 0x6a, 0x3b, 0x8a, 0x21, 0x5c, 0xd7, 0x3a, 0xed, 0x84, 0x8f, 0xdf,
	0x0c, 0xfa, 0x56, 0x4a, 0xe8, 0x70, 0x94, 0x6b, 0xc2, 0x17, 0xe8, 0x37, 0x28, 0xe3, 0xd4, 0xfe,
	0xfa, 0xb9, 0x8f, 0x7d, 0xd4, 0x2f, 0xcd, 0xb2, 0x76, 0x09, 0xbd, 0x3a, 0x08, 0x8c, 0x4a, 0xdb,
	0x03, 0x31, 0x9a, 0x7a, 0x3d, 0x3b, 0x17, 0x2e, 0xa0, 0x5b, 0x51, 0xc1, 0x49, 0x59, 0xe9, 0xb2,
	0x74, 0xd3, 0x9f, 0xe1, 0xb2, 0x86, 0x12, 0x6f, 0xdc, 0xb6, 0x0a, 0xaf, 0xd3, 0xf8, 0x10, 0xe0,
	0x2b, 0x74, 0x93, 0x93, 0x3c, 0x17, 0x74, 0xc4, 0x4f, 0x0d, 0x3b, 0xef, 0x7b, 0x68, 0x8c, 0xc5,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0xe2, 0x87, 0xc7, 0x2e, 0x03, 0x00, 0x00,
}
