global:
  scrape_interval: 10s
  external_labels:
    monitor: 'docker'

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:9180']
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
  - job_name: 'go-service'
    static_configs:
      - targets: ['go-service:4010']
  - job_name: 'node-service'
    static_configs:
      - targets: ['node-service:4020']
