global:
  slack_api_url: "https://hooks.slack.com/services/..."

route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        channel: "#alerts"
        username: "Prometheus"
        text: "Summary: {{ .CommonAnnotations.summary }}\nDescription: {{ .CommonAnnotations.description }}"
