version: "3.4"

services:
  nats:
    image: nats
    hostname: nats
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "-m", "8222", "--user", "nats_client", "--pass", "password?!" ]

  cockroach:
    image: cockroachdb/cockroach
    hostname: cockroach
    container_name: cockroach
    restart: always
    ports:
      - "8080:8080"
      - "26257:26257"
    command: [ "start", "--insecure" ]
  cockroach-init:
    image: cockroachdb/cockroach
    hostname: cockroach-init
    container_name: cockroach-init
    depends_on:
      - cockroach
    environment:
      - COCKROACH_HOST=cockroach
    volumes:
      - "./scripts/cockroach-entrypoint.sh:/cockroach-entrypoint.sh"
    entrypoint: /cockroach-entrypoint.sh

  asset-service:
    image: moorara/asset-service:${VERSION:-latest}
    hostname: asset-service
    container_name: asset-service
    depends_on:
      - nats
      - cockroach
      - cockroach-init
    ports:
      - "4040:4040"
    environment:
      - LOG_LEVEL=debug
      - NATS_SERVERS=nats://nats:4222
      - NATS_USER=nats_client
      - NATS_PASSWORD=password?!
      - COCKROACH_ADDR=cockroach:26257
      - COCKROACH_USER=service
  
  integration-test:
    image: asset-service-test
    hostname: integration-test
    container_name: integration-test
    depends_on:
      - nats
      - cockroach
      - cockroach-init
    environment:
      - INTEGRATION_TEST=true
      - NATS_SERVERS=nats://nats:4222
      - NATS_USER=nats_client
      - NATS_PASSWORD=password?!
      - COCKROACH_ADDR=cockroach:26257
      - COCKROACH_USER=service
    command: [ "go", "test", "-v", "./test/integration" ]
  component-test:
    image: asset-service-test
    hostname: component-test
    container_name: component-test
    depends_on:
      - asset-service
    environment:
      - COMPONENT_TEST=true
      - SERVICE_URL=http://asset-service:4040
    command: [ "go", "test", "-v", "./test/component" ]
