[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/moorara/goto"
  version = "0.1.3"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.14.0"

[[constraint]]
  name = "github.com/uber/jaeger-lib"
  version = "1.5.0"

[prune]
  go-tests = true
  unused-packages = true
