version: "3.4"
services:
  mock-rest:
    image: graphql-server-test
    hostname: mock-rest
    container_name: mock-rest
    ports:
      - "4400:4400"
    command: [ "node", "test/mock/rest/index.js" ]
  mock-grpc:
    image: graphql-server-test
    hostname: mock-grpc
    container_name: mock-grpc
    ports:
      - "4500:4500"
    command: [ "node", "test/mock/grpc/index.js" ]
  graphql-server:
    image: moorara/graphql-server:${VERSION:-latest}
    hostname: graphql-server
    container_name: graphql-server
    depends_on:
      - mock-rest
      - mock-grpc
    ports:
      - "5000:5000"
    environment:
      - LOG_LEVEL=debug
      - SITE_SERVICE_ADDR=mock-rest:4400
      - SENSOR_SERVICE_ADDR=mock-rest:4400
      - SWITCH_SERVICE_ADDR=mock-grpc:4500
  graphql-server-test:
    image: graphql-server-test
    hostname: graphql-server-test
    container_name: graphql-server-test
    depends_on:
      - graphql-server
    environment:
      - SERVICE_URL=http://graphql-server:5000
