version: "3.4"
services:
  mock-server:
    image: graphql-server-test
    hostname: mock-server
    container_name: mock-server
    ports:
      - "4400:4400"
    command: [ "node", "test/mock/index.js" ]
  graphql-server:
    image: moorara/graphql-server:${VERSION:-latest}
    hostname: graphql-server
    container_name: graphql-server
    depends_on:
      - mock-server
    ports:
      - "5000:5000"
    environment:
      - LOG_LEVEL=debug
      - SITE_SERVICE_ADDR=mock-server:4400
      - SENSOR_SERVICE_ADDR=mock-server:4400
  graphql-server-test:
    image: graphql-server-test
    hostname: graphql-server-test
    container_name: graphql-server-test
    depends_on:
      - graphql-server
    environment:
      - SERVICE_URL=http://graphql-server:5000
