version: "3.4"
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    volumes:
      - "./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
  go-service:
    image: moorara/go-service:${VERSION:-latest}
    hostname: go-service
    container_name: go-service
    depends_on:
      - postgres
    ports:
      - "4010:4010"
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_URL=postgres://root:pass@postgres
