version: "3.4"
services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  go-service:
    image: moorara/toys-go-service:${VERSION:-latest}
    hostname: go-service
    container_name: go-service
    depends_on:
      - redis
    ports:
      - "4010:4010"
    environment:
      - LOG_LEVEL=debug
      - REDIS_URL=redis://redis:6379
