apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sensor.fullname" . }}
  labels:
    app: {{ template "sensor.name" . }}
    chart: {{ template "sensor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.postgresql.enabled }}
  postgres-host: {{ printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace | quote }}
  {{- if .Values.postgresql.postgresqlDatabase }}
  postgres-database: {{ .Values.postgresql.postgresqlDatabase | quote }}
  {{- end }}
  {{- if .Values.postgresql.postgresqlUsername }}
  postgres-username: {{ .Values.postgresql.postgresqlUsername | quote }}
  {{- end }}
  {{- else if .Values.postgresql.external.host }}
  postgres-host: {{ .Values.postgresql.external.host | quote }}
  {{- if .Values.postgresql.external.database }}
  postgres-database: {{ .Values.postgresql.external.database | quote }}
  {{- end }}
  {{- if .Values.postgresql.external.username }}
  postgres-username: {{ .Values.postgresql.external.username | quote }}
  {{- end }}
  {{- end }}
