name: Asset
on:
  push:
    paths:
      - 'services/asset/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Linting
        uses: moorara/actions/go-lint@master
        with:
          path: ./services/asset
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Running Unit Tests
        uses: moorara/actions/go-cover@master
        with:
          path: ./services/asset
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building Docker Image
        working-directory: ./services/asset
        run: make docker save-docker
      - name: Upload Docker Image
        uses: actions/upload-artifact@v1
        with:
          name: docker-image
          path: ./services/asset/docker.tar
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building Test Docker Image
        working-directory: ./services/asset
        run: make docker-test
      - name: Running Integration Tests
        working-directory: ./services/asset
        run: make test-integration-docker
  component-tests:
    name: Component Tests
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Docker Image
        uses: actions/download-artifact@v1
        with:
          name: docker-image
      - name: Load Docker Image
        working-directory: ./services/asset
        run: |
          mv ../../docker-image/docker.tar .
          make load-docker
      - name: Building Test Docker Image
        working-directory: ./services/asset
        run: make docker-test
      - name: Running Component Tests
        working-directory: ./services/asset
        run: make test-component-docker
