name: Site
on:
  push:
    paths:
      - 'services/site/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Packages
        working-directory: ./services/site
        run: yarn install
      - name: Linting
        working-directory: ./services/site
        run: yarn run lint
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Packages
        working-directory: ./services/site
        run: yarn install
      - name: Running Unit Tests
        working-directory: ./services/site
        run: yarn run test
      - name: Upload Test Reports
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: ./services/site/coverage
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building Docker Image
        working-directory: ./services/site
        run: make docker save-docker
      - name: Upload Docker Image
        uses: actions/upload-artifact@v1
        with:
          name: docker-image
          path: ./services/site/docker.tar
  component-tests:
    name: Component Tests
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Docker Image
        uses: actions/download-artifact@v1
        with:
          name: docker-image
      - name: Load Docker Image
        working-directory: ./services/site
        run: |
          mv ../../docker-image/docker.tar .
          make load-docker
      - name: Building Test Docker Image
        working-directory: ./services/site
        run: make docker-test
      - name: Running Component Tests
        working-directory: ./services/site
        run: make test-component-docker
